### ISSUE TITLE
Wrong credentials issue

### ISSUE THREAD

**Issue by imtomjorge** [tchenu/myges-to-gcalendar#2]
Hello,

I saw that you're not updating the project any more, but I really liked the idea, as I'm also, an MyGES student.

On the readme file you've said that we must add on the ".env" file our MyGES credentials.

``MYGES_LOGIN=myGesUsername
MYGES_PASSWORD=myGesPassword
MYGES_CLIENT_ID=?
 ``
Could you please confirm me that's the CLIENT ID given by Google API?

Also, could you please confirm me that we have to select "desktop app" during the Google API setup?

Also, if I'm right, when I try to run the script, clicking on the link to get my verification code, get it, paste it, I get the "wrong credential issue".

Do you have any idea about how to solve this?

Looking forward your answer,

Tom

**Comment by tchenu** [comment]
Hi,

I'm sorry, i didn't saw your issue, did you need help anymore ?

`MYGES_CLIENT_ID=skolae-app` will solved your credential issue.

Thibeault
